"""把共享开发模板展开为每版独立、可阅读、可编译的 .cu。不会展开 CUTLASS 库代码。"""
from pathlib import Path
import re
root=Path(__file__).resolve().parents[1]
basic=(root/'include/basic.cuh').read_text();tma=(root/'include/tma.cuh').read_text();ws=(root/'include/warp_specialized.cuh').read_text()
versions=['v01_single_tile','v02_k_loop','v03_multi_cta','v04_tma','v05_double_buffer','v06_persistent','v07_warp_specialized','v08_two_cta','v09_multi_consumer','v09_tuned']
for idx,name in enumerate(versions):
 v=min(idx+1,9)
 if v<=3:
  s=basic.replace('#pragma once\n','').replace('template<int Version,class','template<class').replace('template<int V> void launch_basic','void launch_basic').replace('basic<V,','basic<')
  s=re.sub(r'\bVersion\b|\bV\b',str(v),s)
  call='study::launch_basic(p);'
 elif v<=6:
  types=basic[basic.index('namespace study {'):basic.index('struct BasicStorage')]+ '}\n'
  s=tma.replace('#pragma once\n','').replace('#include "basic.cuh"','#include "common.cuh"\n'+types)
  s=s.replace('template<int V,int S,class','template<class').replace('template<int V,int S>void launch_tma','void launch_tma').replace('tma_kernel<V,S,','tma_kernel<')
  s=re.sub(r'\bV\b',str(v),s);s=re.sub(r'\bS\b',str(1 if v==4 else 2),s)
  call='study::launch_tma(p);'
 else:
  g,c,st=(1,1,4) if v==7 else (2,1,6) if v==8 else (2,2,4)
  ld=tma[tma.index('using LD='):tma.index('template<int Stages>')]
  s=ws.replace('#pragma once\n','').replace('#include "tma.cuh"','#include "common.cuh"\nnamespace study {using namespace cute;\n'+ld+'}\n')
  s=s.replace('template<int G,int C,int Stages>struct WSConfig','struct WSConfig').replace('template<int G> CUTE_DEVICE','CUTE_DEVICE')
  s=s.replace('template<int G,int C,int S,class','template<class').replace('template<int G,int C,int S>void launch_ws','void launch_ws')
  s=s.replace('WSConfig<G,C,S>','WSConfig').replace('mma_arrive<G>','mma_arrive').replace('ws_kernel<G,C,S,','ws_kernel<')
  for key,value in [('G',g),('C',c),('S',st),('Stages',st)]:s=re.sub(r'\b'+key+r'\b',str(value),s)
  call='study::launch_ws(p);'
  # Keep only the actual TMEM load selected by this version.
  wide=name=='v09_tuned'
  s=re.sub(r'#if defined\(STUDY_WIDE_TMEM\)\n(.*?)#else\n(.*?)#endif',lambda m:m[1] if wide else m[2],s,flags=re.S)
 out='// CUDA C++ / CuTe — 原书第 '+str(v)+' 步。\n// Generated by scripts/materialize.py; edit include/ development templates, then regenerate.\n'+s+'\nvoid launch(Problem p){'+call+'}\nconstexpr int VERSION='+str(v)+';\n#include "runner_graph.cuh"\n'
 (root/'kernels'/f'{name}.cu').write_text(out)
