// CUDA C++ / CuTe — 原书第 9 步。
// Generated by scripts/materialize.py; edit include/ development templates,
// then regenerate.
#include "common.cuh"
namespace study {
using namespace cute;
using LD = decltype(group<0, 2>(
    tile_to_shape(UMMA::Layout_K_SW128_Atom<H>{}, Shape<_128, _64>{})));
} // namespace study

namespace study {
struct WSConfig {
  static constexpr int BM = 128 * 2, BN = 128 * 2, Threads = 128 * (2 + 1),
                       Cols = BN * 2;
  using Op = std::conditional_t<
      2 == 1,
      SM100_MMA_F16BF16_SS<H, H, float, 128, 128, UMMA::Major::K,
                           UMMA::Major::K>,
      SM100_MMA_F16BF16_2x1SM_SS<H, H, float, 256, 256, UMMA::Major::K,
                                 UMMA::Major::K>>;
  using MM = decltype(make_tiled_mma(Op{}));
  using T = Shape<Int<BM>, Int<BN>, _64>;
  using AShape = decltype(partition_shape_A(MM{}, Shape<Int<BM>, _64>{}));
  using BShape = decltype(partition_shape_B(MM{}, Shape<Int<BN>, _64>{}));
  using AL = decltype(UMMA::tile_to_mma_shape(UMMA::Layout_K_SW128_Atom<H>{},
                                              AShape{}));
  using BL = decltype(UMMA::tile_to_mma_shape(UMMA::Layout_K_SW128_Atom<H>{},
                                              BShape{}));
  struct Storage {
    alignas(128) ArrayEngine<H, cosize_v<AL>> a[4][2];
    alignas(128) ArrayEngine<H, cosize_v<BL>> b[4];
    alignas(128) ArrayEngine<H, cosize_v<LD>> d[2];
    alignas(16) uint64_t full[4], empty[4], acc_full[2], acc_empty[2];
    alignas(16) uint32_t tmem;
  };
};
CUTE_DEVICE void mma_arrive(uint64_t *bar) {
  if constexpr (2 == 1)
    cutlass::arch::umma_arrive(bar);
  else
    cutlass::arch::umma_arrive_multicast_2x1SM(bar, 3);
}
template <class TA, class TB, class TD, class CA, class CB, class CD>
__global__ void ws_kernel(TA a, TB b, TD d, CUTE_GRID_CONSTANT CA const ca,
                          CUTE_GRID_CONSTANT CB const cb,
                          CUTE_GRID_CONSTANT CD const cd, int mt, int nt) {
  using CF = WSConfig;
  using MM = typename CF::MM;
  using Tile = typename CF::T;
  using AL = typename CF::AL;
  using BL = typename CF::BL;
  extern __shared__ char buf[];
  auto &s = *reinterpret_cast<typename CF::Storage *>(buf);
  int warp = threadIdx.x / 32, peer = blockIdx.x % 2, cluster = blockIdx.x / 2,
      cluster_count = gridDim.x / 2;
  bool leader = peer == 0, elected = elect_one_sync();
  MM mma;
  auto cta = mma.get_slice(peer);
  using Alloc =
      std::conditional_t<2 == 1, TMEM::Allocator1Sm, TMEM::Allocator2Sm>;
  Alloc alloc;
  if (warp == 0)
    alloc.allocate(CF::Cols, &s.tmem);
  if (threadIdx.x == 0) {
    for (int i = 0; i < 4; ++i) {
      initialize_barrier(s.full[i], 1);
      initialize_barrier(s.empty[i], 2);
    }
    for (int i = 0; i < 2; ++i) {
      initialize_barrier(s.acc_full[i], 1);
      initialize_barrier(s.acc_empty[i], 128 * 2);
    }
  }
  if constexpr (2 == 2)
    cluster_sync();
  else
    __syncthreads();
  // Producer warp: fills a ring. A stage is reusable only after MMA releases
  // it.
  if (warp == 4 * 2 + 3) {
    int iteration = 0;
    for (int ti = cluster; ti < mt * nt; ti += cluster_count) {
      int bm, bn;
      grouped_tile(ti, mt, nt, bm, bn);
      for (int kt = 0; kt < size<1>(a) / 64; ++kt, ++iteration) {
        int st = iteration % 4;
        if (iteration >= 4)
          wait_barrier(s.empty[st], ((iteration / 4) - 1) & 1);
        if (elected) {
          if (leader)
            set_barrier_transaction_bytes(
                s.full[st], 2 * (2 * cosize_v<AL> + cosize_v<BL>)*sizeof(H));
          CUTE_UNROLL
          for (int c = 0; c < 2; ++c) {
            auto ga = local_tile(a, Tile{}, make_coord(bm * 2 + c, bn, _),
                                 Step<_1, X, _1>{});
            auto pa = cta.partition_A(ga);
            auto sa = make_tensor(make_smem_ptr(s.a[st][c].begin()), AL{});
            auto [ag, as] =
                tma_partition(ca, _0{}, Layout<_1>{}, group_modes<0, 3>(sa),
                              group_modes<0, 3>(pa));
            copy(ca.with(s.full[st]), ag(_, kt), as);
          }
          auto gb = local_tile(b, Tile{}, make_coord(bm * 2, bn, _),
                               Step<X, _1, _1>{});
          auto pb = cta.partition_B(gb);
          auto sb = make_tensor(make_smem_ptr(s.b[st].begin()), BL{});
          auto [bg, bs] =
              tma_partition(cb, _0{}, Layout<_1>{}, group_modes<0, 3>(sb),
                            group_modes<0, 3>(pb));
          copy(cb.with(s.full[st]), bg(_, kt), bs);
        }
      }
    }
  }
  // Exactly 2 independent MMA issue warps, matching the book's consumer
  // definition.
  if (warp >= 4 * 2 && warp < 4 * 2 + 2 && leader) {
    int c = warp - 4 * 2;
    int iteration = 0, round = 0;
    for (int ti = cluster; ti < mt * nt; ti += cluster_count, ++round) {
      int bm, bn;
      grouped_tile(ti, mt, nt, bm, bn);
      auto gd = local_tile(d, Tile{}, make_coord(bm * 2 + c, bn, _),
                           Step<_1, _1, X>{});
      auto pd = cta.partition_C(gd);
      auto acc = cta.make_fragment_C(pd);
      acc.data() = s.tmem + c * CF::BN;
      if (round)
        wait_barrier(s.acc_empty[c], (round - 1) & 1);
      mma.accumulate_ = UMMA::ScaleOut::Zero;
      for (int kt = 0; kt < size<1>(a) / 64; ++kt, ++iteration) {
        int st = iteration % 4;
        wait_barrier(s.full[st], (iteration / 4) & 1);
        auto sb = make_tensor(make_smem_ptr(s.b[st].begin()), BL{});
        auto rb = cta.make_fragment_B(sb);
        auto sa = make_tensor(make_smem_ptr(s.a[st][c].begin()), AL{});
        auto ra = cta.make_fragment_A(sa);
        CUTE_UNROLL
        for (int kb = 0; kb < size<2>(ra); ++kb) {
          gemm(mma, ra(_, _, kb), rb(_, _, kb), acc);
          mma.accumulate_ = UMMA::ScaleOut::One;
        }
        // Every consumer signals once: producer expects 2 completions before
        // reusing A/B.
        mma_arrive(&s.empty[st]);
      }
      mma_arrive(&s.acc_full[c]);
    }
  }
  // Each consumer warpgroup writes one accumulator tile through its own SMEM
  // buffer.
  if (threadIdx.x < 128 * 2) {
    int c = threadIdx.x / 128, tid = threadIdx.x % 128, round = 0;
    for (int ti = cluster; ti < mt * nt; ti += cluster_count, ++round) {
      int bm, bn;
      grouped_tile(ti, mt, nt, bm, bn);
      auto gd = local_tile(d, Tile{}, make_coord(bm * 2 + c, bn, _),
                           Step<_1, _1, X>{});
      auto pd = cta.partition_C(gd);
      auto acc = cta.make_fragment_C(pd);
      acc.data() = s.tmem + c * CF::BN;
      wait_barrier(s.acc_full[c], round & 1);
      auto ae = zipped_divide(acc, make_tile(Shape<_128, _64>{}));
      auto de = zipped_divide(pd, make_tile(Shape<_128, _64>{}));
      auto sd = make_tensor(make_smem_ptr(s.d[c].begin()), LD{});
      auto [dg, ds] = tma_partition(cd, sd, de);
      auto cp = make_tmem_copy(SM100_TMEM_LOAD_32dp32b1x{}, ae(_, _0{}));

      auto th = cp.get_slice(tid);
      auto src = th.partition_S(ae);
      auto dst = th.partition_D(sd);
      auto rf = make_tensor<float>(shape(dst));
      auto rh = make_fragment_like(dst);
      for (int ei = 0; ei < size<2>(src); ++ei) {
        copy(cp, src(_, _, ei), rf);
        cutlass::arch::fence_view_async_tmem_load();
        CUTE_UNROLL
        for (int j = 0; j < size(rh); ++j)
          rh(j) = H(rf(j));
        copy(rh, dst);
        tma_store_fence();
        cutlass::arch::NamedBarrier::sync(128, c);
        if (tid == 0) {
          copy(cd, ds, dg(_, ei));
          tma_store_arrive();
          tma_store_wait<0>();
        }
        cutlass::arch::NamedBarrier::sync(128, c);
      }
      if constexpr (2 == 2)
        cutlass::arch::ClusterBarrier::arrive(&s.acc_empty[c], 0, 1);
      else
        cutlass::arch::ClusterBarrier::arrive(&s.acc_empty[c]);
    }
  }
  if constexpr (2 == 2)
    cluster_sync();
  else
    __syncthreads();
  if (warp == 0) {
    alloc.release_allocation_lock();
    alloc.free(s.tmem, CF::Cols);
  }
}
void launch_ws(Problem p) {
  using CF = WSConfig;
  using MM = typename CF::MM;
  using Tile = typename CF::T;
  auto a = make_tensor(make_gmem_ptr(p.a), make_layout(make_shape(p.m, p.k),
                                                       make_stride(p.k, _1{})));
  auto b = make_tensor(make_gmem_ptr(p.b), make_layout(make_shape(p.n, p.k),
                                                       make_stride(p.k, _1{})));
  auto d = make_tensor(make_gmem_ptr(p.d), make_layout(make_shape(p.m, p.n),
                                                       make_stride(p.n, _1{})));
  auto cluster_layout = tiled_divide(make_layout(Shape<Int<2>, _1, _1>{}),
                                     make_tile(typename MM::AtomThrID{}));
  using CopyOp = std::conditional_t<2 == 1, SM90_TMA_LOAD, SM100_TMA_2SM_LOAD>;
  auto ca = make_tma_atom_A_sm100(CopyOp{}, a, typename CF::AL{}, Tile{}, MM{},
                                  cluster_layout);
  auto cb = make_tma_atom_B_sm100(CopyOp{}, b, typename CF::BL{}, Tile{}, MM{},
                                  cluster_layout);
  auto cd = make_tma_atom(SM90_TMA_STORE{}, d, LD{}, Shape<_128, _64>{});
  auto ta = ca.get_tma_tensor(shape(a));
  auto tb = cb.get_tma_tensor(shape(b));
  auto td = cd.get_tma_tensor(shape(d));
  auto fn = ws_kernel<decltype(ta), decltype(tb), decltype(td), decltype(ca),
                      decltype(cb), decltype(cd)>;
  static bool configured = false;
  if (!configured) {
    CUDA_OK(cudaFuncSetAttribute(fn,
                                 cudaFuncAttributeMaxDynamicSharedMemorySize,
                                 sizeof(typename CF::Storage)));
    configured = true;
  }
  int mt = p.m / (CF::BM * 2), nt = p.n / CF::BN;
  int clusters = std::min(mt * nt, p.sms / 2);
  if constexpr (2 == 1)
    fn<<<clusters, CF::Threads, sizeof(typename CF::Storage)>>>(ta, tb, td, ca,
                                                                cb, cd, mt, nt);
  else {
    cudaLaunchConfig_t config{};
    config.gridDim = dim3(clusters * 2);
    config.blockDim = dim3(CF::Threads);
    config.dynamicSmemBytes = sizeof(typename CF::Storage);
    config.stream = cudaStreamPerThread;
    cudaLaunchAttribute attr{};
    attr.id = cudaLaunchAttributeClusterDimension;
    attr.val.clusterDim = {2, 1, 1};
    config.attrs = &attr;
    config.numAttrs = 1;
    CUDA_OK(cudaLaunchKernelEx(&config, fn, ta, tb, td, ca, cb, cd, mt, nt));
  }
}
} // namespace study

void launch(Problem p) { study::launch_ws(p); }
constexpr int VERSION = 9;
#include "runner_graph.cuh"
